### ISSUE TITLE
Groups move around when you apply to one.

### ISSUE THREAD

**Issue by Revnn** [Jods-GH/GroupFinderRIO#8] opened 2024-09-15 16:29 UTC
### Description

I click on a group to apply just to the addon change to another group completely and i end up applying to the wrong group.
Only happening with this addon turned on.

### World of Warcraft Flavor

Retail (Default)

### Reproduction Steps

click on a group to apply
you'll end up applying to another random group because the addon moved the groups around on the list.

**Comment by Jodsderechte** [comment] 2024-09-15 16:38
duplicate of #6 please update the addon

**Comment by Revnn** [comment] 2024-09-15 16:41
It is actually updated.

**Comment by Jodsderechte** [comment] 2024-09-15 16:42
Which version are you running?

**Comment by Revnn** [comment] 2024-09-15 16:43
1.1.3a

**Comment by Jodsderechte** [comment] 2024-09-15 16:44
What view does this happen in? Dungeon tab? Raid tab?

**Comment by Jodsderechte** [comment] 2024-09-15 16:47
You are right for some reason that keeps happening in some cases when i filter for a specific dungeon

**Closed** 2024-09-15 16:57 UTC
Labels: bug
