### ISSUE TITLE
New bugs new patch

### ISSUE THREAD

**Issue by reyard** [Jods-GH/GroupFinderRIO#17] opened 2024-12-19 04:24 UTC
### Description

Open LFG window and get issues.

### World of Warcraft Flavor

Retail (Default)

### Lua Error

955x bad argument #1 to '?' (Usage: local activityInfo = C_LFGList.GetActivityInfoTable(activityID [, questID, showWarmode]))
[string "=[C]"]: in function `GetActivityInfoTable'
[string "@GroupFinderRio/GroupFinderRio.lua"]:370: in function <GroupFinderRio/GroupFinderRio.lua:365>
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: ?
[string "=[C]"]: in function `LFGListSearchEntry_Update'
[string "@Blizzard_GroupFinder/Mainline/LFGList.lua"]:2619: in function `initializer'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:374: in function `InvokeInitializer'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:392: in function <...izzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua:391>
[string "=[C]"]: in function `secureexecuterange'
...
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:319: in function `SignalDataChangeEvent'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBoxListView.lua"]:299: in function `SetDataProvider'
[string "@Blizzard_SharedXML/Shared/Scroll/ScrollBox.lua"]:639: in function `SetDataProvider'
[string "@Blizzard_GroupFinder/Mainline/LFGList.lua"]:2663: in function <...aceBlizzard_GroupFinder/Mainline/LFGList.lua:2622>
[string "=[C]"]: ?
[string "=[C]"]: in function `LFGListSearchPanel_UpdateResults'
[string "@Blizzard_GroupFinder/Mainline/LFGList.lua"]:2593: in function <...aceBlizzard_GroupFinder/Mainline/LFGList.lua:2589>
[string "=[C]"]: in function `LFGListSearchPanel_UpdateResultList'
[string "@Blizzard_GroupFinder/Mainline/LFGList.lua"]:2211: in function `onEvent'
[string "@Blizzard_GroupFinder/Mainline/LFGList.lua"]:262: in function <...aceBlizzard_GroupFinder/Mainline/LFGList.lua:171>

Locals:
(*temporary) = "bad argument #1 to '?' (Usage: local activityInfo = C_LFGList.GetActivityInfoTable(activityID [, questID, showWarmode]))"

### Reproduction Steps

1 open LFG window
2 find a new group

**Comment by Jodsderechte** [comment] 2024-12-19 07:01
Duplicate of #16

**Closed by Jodsderechte** 2024-12-19 07:01 UTC
Labels: bug
